### ISSUE TITLE
ユーザ向けの一覧ページ作成

### ISSUE THREAD

**Issue by sugumura** [sugumura/photo-share-app#25]
参考

https://github.com/sugumura/photo-share-app/assets/404086/dcd2a79d-970f-41f3-bad8-3ab388508a61

**Comment by kei4eva4** [comment]
ソースコード
[instagram-app-search-screen-1665227165.zip](https://github.com/user-attachments/files/15543479/instagram-app-search-screen-1665227165.zip)

**Comment by sugumura** [comment]
実装済みのためクローズ
https://photo-share-app-ten.vercel.app/gallery
