### ISSUE TITLE
LINEで友達追加時に使い方の説明

### ISSUE THREAD

**Issue by sugumura** [sugumura/photo-share-app#7]
デフォルトメッセージなので良い感じに使い方を書いてほしい

**Comment by ksk001100** [comment]
https://developers.line.biz/ja/docs/messaging-api/building-bot/#set-greeting-message

**Comment by sugumura** [comment]
![Screenshot_20240602-150339.png](https://github.com/sugumura/photo-share-app/assets/404086/a9360611-c502-46f4-b05e-7cdb3fd7ef24)
